language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
script:
 - ./runSonarQubeAnalysis.sh
#- if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
#    sonar-scanner -Dsonar.login=$SONAR_TOKEN -e -X
#  else
#    make
#  fi
branches:
  only:
  - master
addons:
  sonarqube: true
  apt:
    packages:
    - libssl-dev
