language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
script:
#- if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
 -   sonar-scanner -Dsonar.login=$SONAR_TOKEN
#  else
#    make
#  fi
branches:
  only:
  - master
addons:
  sonarqube: true
  apt:
    packages:
    - libssl-dev
